"""empty message

Revision ID: 24985e25c569
Revises: 6cfe723cadd2
Create Date: 2020-12-06 17:53:59.414971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24985e25c569'
down_revision = '6cfe723cadd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instrument_label'), 'instrument', ['label'], unique=True)
    op.create_table('joiner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('instrumentId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instrumentId'], ['instrument.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('warmups', sa.Text(), nullable=True),
    sa.Column('repertoire', sa.Text(), nullable=True),
    sa.Column('userToInstrumentId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userToInstrumentId'], ['joiner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regiment')
    op.drop_table('joiner')
    op.drop_index(op.f('ix_instrument_label'), table_name='instrument')
    op.drop_table('instrument')
    # ### end Alembic commands ###
