"""empty message

Revision ID: 2b4097d89cd0
Revises: 7733855ec5f4
Create Date: 2020-12-06 20:00:39.942662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b4097d89cd0'
down_revision = '7733855ec5f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('joiner')
    op.add_column('instrument', sa.Column('defaultGoalInSeconds', sa.Integer(), nullable=True))
    op.add_column('instrument', sa.Column('userId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'instrument', 'user', ['userId'], ['id'])
    op.add_column('regiment', sa.Column('instrumentId', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'regiment', type_='foreignkey')
    op.create_foreign_key(None, 'regiment', 'instrument', ['instrumentId'], ['id'])
    op.drop_column('regiment', 'userToInstrumentId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regiment', sa.Column('userToInstrumentId', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'regiment', type_='foreignkey')
    op.create_foreign_key(None, 'regiment', 'joiner', ['userToInstrumentId'], ['id'])
    op.drop_column('regiment', 'instrumentId')
    op.drop_constraint(None, 'instrument', type_='foreignkey')
    op.drop_column('instrument', 'userId')
    op.drop_column('instrument', 'defaultGoalInSeconds')
    op.create_table('joiner',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('userId', sa.INTEGER(), nullable=True),
    sa.Column('instrumentId', sa.INTEGER(), nullable=True),
    sa.Column('defaultGoalInSeconds', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['instrumentId'], ['instrument.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
