"""empty message

Revision ID: 7733855ec5f4
Revises: 5d529408932a
Create Date: 2020-12-06 19:22:11.879471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7733855ec5f4'
down_revision = '5d529408932a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('joiner', sa.Column('defaultGoalInSeconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('joiner', 'defaultGoalInSeconds')
    # ### end Alembic commands ###
