"""empty message

Revision ID: b4c66a515512
Revises: 
Create Date: 2020-12-07 09:54:58.252952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4c66a515512'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('defaultGoalInMinutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instrument_label'), 'instrument', ['label'], unique=True)
    op.create_table('regiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('warmups', sa.Text(), nullable=True),
    sa.Column('repertoire', sa.Text(), nullable=True),
    sa.Column('goalInMinutes', sa.Integer(), nullable=True),
    sa.Column('timeElapsedInSeconds', sa.Integer(), nullable=True),
    sa.Column('instrumentId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instrumentId'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regiment')
    op.drop_index(op.f('ix_instrument_label'), table_name='instrument')
    op.drop_table('instrument')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
